INSERT INTO User(nachname, vorname, username, adresse, email, password, role, salt) VALUES('admin', 'admin', 'admin', 'Adminstrasse 21', 'admin@admin.com', '99159a070b769bd1b44cd05f866418bdf8ea5b0fffad62179aecd329f1aff373b84c94e96a9c7e9575523e21eeba28a5e091f1ba242f186f053be6c15e7fb8ee', 'ADMIN', '2343rep');
INSERT INTO User(nachname, vorname, username, adresse, email, password, role, salt) VALUES('test', 'test', 'test', 'Adminstrasse 14', 'testuser@test.com', '1950619afddbb2061a50284a7114301a6eaff370e66fdf8d5823c7014e51bcb34b01cbc00d0a424628ca2dc5c08e693d07974dc2a3ea4c1c5e27f3a3a436ff21', 'STUDENT', '237cmr1');


INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('Boruto Tome 1', 'A manga about the story of the naruto son Boruto', 'Masashi Kishimoto', 'Shonen Jump', 'MANGAS','2015', 'Several years after the end of the Shinobi War, Narutos son Boruto is about to enter the Chûnin exams alongside Sarada Uchiha and the mysterious Mitsuki.');

INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('One Piece Stampede', 'Relating the adventure of luffy and his teammates during the pirate festival', 'Shonen Jump', 'Eiichiro Oda', 'MANGAS', '2019', 'Ruffy und die Crew besuchen eine Piraten-Expo. Der Veranstaltung der Messe, Buena Festa, hat sie hoechstpersoenlich eingeladen. In den verschiedenen Pavillons treffen sie die besten und schlimmsten Piraten, doch dann decken sie eine Verschwoerung auf.');

INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('Methamatik fuer Informatiker : Analysis ans Statistik', 'Buch bezueglich die Statistiken und Analysis', 'Gerald Teschl und Susanne Teschl', 'Springer','MATHS','2007', 'In diesem Lehrbuch werden die mathematischen Grundlagen exakt und dennoch anschaulich und gut nachvollziehbar vermittelt. Sie werden durchgehend anhand zahlreicher Musterbeispiele illustriert, durch Anwendungen in der Informatik motiviert und durch historische Hintergruende oder Ausblicke in angrenzende Themengebiete aufgelockert. Am Ende jedes Kapitels befinden sich Kontrollfragen, die das Verstaendnis testen und typische Fehler bzw. Missverstaendnisse ausraeumen. Zusaetzlich helfen zahlreiche Aufwaermuebungen (mit vollstaendigem Loesungsweg) und weiterfuehrende Uebungsaufgaben das Erlernte zu festigen und praxisrelevant umzusetzen. Dieses Lehrbuch ist daher auch sehr gut zum Selbststudium geeignet. Ergaenzend wird in eigenen Abschnitten das Computeralgebrasystem Mathematica vorgestellt und eingesetzt, wodurch der Lehrstoff visualisiert und somit das Verstaendnis erleichtert werden kann.' );

INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('Statistik II fuer Dummies', 'Statics lernen', 'Deborah Rumsey und Judith Muhr', 'Wiley-VCH Verlag GmbH','MATHS','2012', 'Es gibt Qualen, verdammte Qualen und Statistik, so sehen es viele Studenten. Mit Statistik II fuer Dummies lernen Sie so leicht wie moeglich. Deborah Rumsey zeigt Ihnen, wie Sie Varianzanalysen und Chi-Quadrat-Test machen, wie Sie mit Regressionen arbeiten, ein Modell erstellen, Korrelationen bilden und vieles mehr.So lernen Sie die Methoden, die Sie brauchen, und erhalten das Handwerkszeug, erfolgreich Ihre Statistikpruefungen zu bestehen.' );

INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('Aufgaben und Loesungen zur Hoeheren Mathematik 1', 'Aufgaben und loesungen zur Hoeheren Mathematik 1', 'Klaus Hoellig und Joerg Hoerner', 'Springer','MATHS', '2018', 'Mehr als 500 typische Klausur- und Uebungsaufgaben zur Hoeheren Mathematik fuer Ingenieure, Natur- und Wirtschaftswissenschaftler mit detaillierten Loesungen ermoeglichen eine optimale Vorbereitung auf Pruefungen und erleichtern die Bearbeitung von Uebungsblaettern.Die wesentlich erweiterte, in drei Baende gegliederte zweite Auflage enthaelt ebenfalls Aufgaben, die den Einsatz von MATLAB(R)und Maple(TM) bei zentralen mathematischen Problemstellungen illustrieren.' );
       
INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('Mit Mathe richtig anfangen','Eine Einfuehrung mit integrierter Anwendung der Programmiersprache Python', 'Peter Knabner, Balthasar Reuter und Raphael Schulz','Springer','MATHS','2019', 'Das Buch gliedert sich in zwei Teile. Im ersten Teil wird in die Grundlagen des logischen Arbeitens eingefuehrt: Mathematik hat mit Logik zu tun, aber wie genau und was ist Logik? Was ist die Basis fuer mathematisches Denken, wann sind mathematische Gedankengaenge praezise und wie drueckt man sie aus und schreibt sie auf? Im zweiten Teil geht es um die Frage, was Zahlen eigentlich sind und woher sie kommen. Von den natuerlichen ueber die ganzen und rationalen Zahlen fuehrt der Weg zu den reellen Zahlen, die sich meist als Dezimalzahl nicht mehr exakt hinschreiben, sondern nur noch beliebig genau approximieren lassen. Solche Rechenverfahren laesst man besser Computer ausfuehren, daher wird parallel zur Mathematik auch in das Programmieren mit Python eingefuehrt.');

INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('Einfuehrung in die Funktionalanalysis', 'Buch bezueglich die Funktionsnalysis', 'Christian Clason', 'Birkhaeuser','MATHS', '2019', 'Das vorliegende Lehrbuch bietet eine kompakte Einfuehrung in die Theorie und ist begleitend fuer eine vierstuendige Vorlesung im Bachelorstudium konzipiert. Es spannt den Bogen von den topologischen Grundlagen aus der Analysis-Grundvorlesung bis zur Spektraltheorie in Hilbertraeumen; besondere Aufmerksamkeit wird dabei den zentralen Resultaten ueber Dualraeume und schwache Konvergenz geschenkt.' );

INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('Theoretische Informatik', 'Informatik zugrundeliegenden Konzepte', 'Lutz Priese und Katrin Erk', 'Springer','PROGRAMMING', '2018', 'Die Theoretische Informatik untersucht die der Informatik zugrundeliegenden Konzepte, Modelle und Vorgehensweisen. Es ist ein Fachgebiet, das durch seine formalen Definitionen und vielen Beweise Parallelen zur Mathematik aufweist. Dieses Buch fuehrt umfassend in die Theoretische Informatik ein. Dabei legen die Autoren besonderen Wert auf Verstaendlichkeit und gute Lesbarkeit. Zu Beginn stellen sie die mathematischen Konzepte mit ihren Begriffen und Notationen vor. In den folgenden drei Hauptabschnitten fuehrt das Buch in die Theorie der formalen Sprachen und in die Theorie der Berechenbarkeit ein und gibt einen Ueberblick ueber die Komplexitaetstheorie. Mit ihren verschiedenen Sprachklassen, Grammatiken und den Automaten werden die formalen Sprachen einerseits eingesetzt, um Compiler zu bauen und andererseits um Programme zu analysieren. Bei der Anwendung der Theorie der Berechenbarkeit werden Modelle eines Computers wie etwa die Registermaschine betrachtet. Weil sie einfacher aufgebaut sind als ein konkreter Computer, kann an ihnen untersucht werden, ob ein Problem ueberhaupt mit einem Computer geloest werden kann. Auch alternative Rechenmodelle wie Zwei-Register-Maschinen, Tag-Systeme, Wang-Maschinen, Roedding-Netze, Splicing und reversible Rechnungen kommen in einem eigenen umfangreichen Kapitel zur Sprache. Abschliessend wird die Komplexitaetstheorie betrachtet, anhand derer sich herausfinden laesst, wie viel Rechenzeit fuer die Loesung eines Problems aufgewendet werden muss.' );

INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('Informatik: Eine praktische Einfuehrung mit Bash und Python', 'Bash und Python lernen', 'Tobias Haeberlein', 'De Gruyter Oldenbourg', 'PROGRAMMING', '2016', 'Die Praxis der Informatik lebt vom Ausprobieren verschiedener Loesungswege, vom Experimentieren mit Programmkonstrukten und Algorithmen und, im Allgemeinen, von der praktischen Erforschung. Im Mittelpunkt der Lehrmethode dieses Lehrbuchs steht der "Do it yourself"-Ansatz: Durch das Loesen zahlreicher Uebungen erlebt und arbeitet der Schueler persoenlich mit den zu vermittelnden Konzepten und lernt, Informatikprobleme wirklich zu verstehen.' );

INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('Lexikon der Informatik', 'Querverweise und thematisch vernetzte Begriffserklaerungen', 'Peter Fischer und Peter Hofer', 'Springer','PROGRAMMING', '2007', 'Begriffskompetenz in der Informatik: Das Lexikon der Informatik vermittelt die heute notwendige Sicherheit im Umgang mit der Begriffswelt der Informatik. Die Auswahl der ueber 6000 Kurzdefinitionen unter mehr als 5000 Stichworten ist repraesentativ und aktuell, wobei auf die Erwaehnung von Produkten und kurzlebigen Kenndaten weitestgehend verzichtet wird' );

INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('Grundlagen der Technischen Informatik', 'Einfuuehrung in die Grundlagen der technischen Informatik.', 'Hoffmann und Dirk W', 'Hanser Fachbuchverlag','PROGRAMMING','2014', 'Zahlreiche Uebungsaufgaben zur Vertiefung der Lerninhalte. Viele aktuelle Anwendungsbeispiele und Praxisbezuege. Umfassende Einfuehrung in die Grundlagen der technischen Informatik. Zahlreiche Uebungsaufgaben zur Vertiefung der Lerninhalte. Viele aktuelle Anwendungsbeispiele und Praxisbezuege.' );

INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('Numerik fuer Ingenieure, Physiker und Informatiker', 'Buch bezueglich Physik und Informatik', 'Guenter Baerwolff', 'Springer','PROGRAMMING','2016', 'Dieses Lehrbuch wendet sich hauptsaechlich an Studierende der Ingenieur- und Naturwissenschaften sowie der Informatik, aber auch an in der angewandten Praxis taetige Absolventen dieser Disziplinen. Es wird ein weites Spektrum von verschiedenen Themenfeldern behandelt, von der numerischen Loesung linearer Gleichungssysteme ueber Eigenwertprobleme, numerische Integration bis hin zu gewoehnlichen und partiellen Differentialgleichungen. Dabei werden jeweils die Methoden diskutiert, die den spezifischen Anforderungen typischer Aufgabenstellungen in der Praxis entsprechen. Der  Autor stellt die Themen in einer Weise dar, die sowohl den wesentlichen mathematischen Hintergrund klar macht, als auch eine unkomplizierte Umsetzung auf praktische Aufgabenstellungen bzw. die Realisierung auf dem Computer ermoeglicht.' );

INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('Biologie fuer Mediziner', 'Grundlagen fuer das Medizinstudium', 'Werner Buselmaier und Joana Haussig', 'Springer','SCIENCE','2018', 'Dieses Lehrbuch gibt Ihnen einen vollstaendigen Ueberblick ueber alle biologischen Grundlagen fuer das Medizinstudium. Alle IMPP Pruefungsthemen sind abgedeckt und die Inhalte eng am GK orientiert um Sie effizient auf die Pruefung vorzubereiten. Zahlreiche klinische Beispiele verdeutlichen den Praxisbezug und die bewaehrte Didaktik hilft beim Verstaendnis und Lernen. Profitieren Sie von der langjaehrigen Erfahrung der Dozenten, die sorgfaeltig das Wesentliche fuer Sie ausgewaehlt und aufbereitet haben. Der Inhalt, Zusammenfassungen und Merksaetze erleichtern das Lernen, Zahlreiche Abbildungen und Tabellen zum schnellen Verstaendnis, Erweiterungen um neueste wissenschaftliche Methoden und Erkenntnisse und Viele klinische Bezuege veranschaulichen den praktischen Bezug.' );

INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('Methoden der Bioinformatik: Eine Einfuehrung zur Anwendung in Biologie und Medizin', 'Buch bezueglich die Biologie und Medezin', 'Marc-Thorsten Huett und Manuel Dehnert', 'Springer','SCIENCE', '2016', 'Die Autoren fuehren den Leser von den mathematischen Grundlagen zu den konkreten Methoden der Bioinformatik. Das Buch wendet sich damit an alle, die bioinformatische Methoden und Softwarepakete verwenden wollen, sie aber nicht als Black Boxes akzeptieren moechten. Ein besonderes Highlight ist die schrittweise Implementierung wichtiger Algorithmen der Bioinformatik im Computeralgebra-Programm Mathematica, um die Konzepte auch auf der informatischen Ebene zu verstehen. Das Themenspektrum reicht von bioinformatischen Alltagsfragen bis in die Systembiologie.' );

INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('Biologie der Sinne: Vom Molekuel zur Wahrnehmung', 'Buch bezueglich die entwicklung die sinnorgane', 'Stephan Frings und Frank Mueller', 'Springer', 'SCIENCE', '2014', 'In diesem Sachbuch wird allgemeinverstaendlich dargelegt, wie hoch entwickelt die Sinnesorgane bei Tieren und Menschen sind. Oft erreichen Sinnesleistungen die Grenze des physikalisch Moeglichen. Das Buch erklaert, wie Sinnesreize erfasst werden, wie sie in die Sprache des Nervensystems uebersetzt werden und wie unser Gehirn Sinnesinformation verarbeitet. Das Gehirn setzt dabei auf wohl bewaehrte Strategien, die ein Ziel verfolgen: die Ueberlebenschance des Organismus zu erhoehen. Deshalb wird in diesem Buch gezeigt, wie sehr die Sinnesleistungen durch die Evolution geformt und bestimmt wurden. Das Buch zeigt auch, dass viele Tiere ihre Umwelt vollkommen anders wahrnehmen als wir.' );

INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('Das Phaenomen Leben: Grundfragen der Theoretischen Biologie', 'Buch bezueglich Form die naturwissenschaftlichen Grundprinzipien', 'Anita Schoebel', 'Springer','SCIENCE', '2016', 'Der renommierte Tierphysiologe Heinz Penzlin behandelt in diesem Buch, das hier in zweiter Auflage vorgelegt wird, in systematischer und uebersichtlicher Form die naturwissenschaftlichen Grundprinzipien, die alleLebewesen  trotz ihrer enormen Formenvielfalt  gleichermassen kennzeichnen. Das Buch ist keine Biophilosophie, sondern richtet sich an alle, die an den wissenschaftlichen Grundlagen des Phaenomens „Leben“ aus heutiger Sicht interessiert sind. „Leben“ wird als die Leistung einzigartiger offener Systeme betrachtet, die in der Lage sind, ihre interne teleonome Organisation auf der Grundlage gespeicherter und abrufbarer genetischer Informationen selbsttaetig aufrechtzuerhalten und an die naechste Generation weiterzugeben.' );

INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('Mathematik in der Biologie', 'Buch bezueglich die Einsatz con Mathematik in der Biologie', 'Annika Eickhoff-Schachtebeck und Anita Schoebel', 'Springer', 'SCIENCE', '2014', 'Das Buch fuehrt in die Grundbegriffe der Mathematik ein, wie sie in biologischen Studiengaengen benoetigt und verwendet werden. Dabei werden von Anfang an Zusammenhaenge zur Biologie hergestellt und die mathematischen Begriffe und Resultate an Beispielen mit biologischem, chemischem oder medizinischem Bezug illustriert. Neben dem ueblichen Standardstoff ueber Funktionen, Folgen, Gleichungen, Diffferenzieren und Integrieren werden auch Netzwerke behandelt. Jedes Kapitel wird mit einer Zusammenfassung, einem Kurztest und Uebungsaufgaben abgeschlossen.' );

INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('Physik: fuer Wissenschaftler und Ingenieure', 'Einfuehrung in die Experimentalphysik', 'Paul A. Tipler, Gene Mosca und Jenny Wagner', 'Springer','PHYSIC', '2015', 'Verstaendlich, einpraegsam, lebendig und die perfekte Pruefungsvorbereitung, mit unzaehligen relevanten Rechenbeispielen und Aufgaben dies ist Tiplers bekannte und beliebte Einfuehrung in die Experimentalphysik. Klar und eingaengig fuehrt Tipler den Leser durch die physikalische Begriffs- und Formelwelt illustriert von unzaehligen liebevoll gestalteten Farbgrafiken. Studienanfaenger  egal, ob sie Physik im Hauptfach studieren oder ob es als Nebenfach auf dem Lehrplan steht  finden hier Schritt fuer Schritt den klar verstaendlichen Einstieg in die Physik mittels, Verstaendlicher Aufarbeitung des Pruefungsstoffes, Zahlreichen pruefungsrelevanten Uebungsaufgaben und Anschaulichen Grafiken' );

INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('Theoretische Physik 1 Mechanik', 'Buch bezueglich Theorische Physik', 'Dieter Luest, Anton Rebhan, Andreas Wipf', 'Springer','PHYSIC', '2018', 'Das beliebte Buch Theoretische Physik wird jetzt erstmalig in korrigierter und ergaenzter Form in Einzelbaenden angeboten. Das ermoeglicht den Studierenden, die handlichen Baende zum Lernen, Aufgabenloesen und zum schnellen Nachschlagen leichter mitnehmen und nutzen zu koennen. Gleichzeitig wird die gesamte theoretische Physik des Bachelorstudiums (und darueber hinaus) in den vier Baenden aufeinander abgestimmt praesentiert. Das vorliegende Buch ist der erste Teil der vierbaendigen Reihe und deckt den Lehrstoff der Bachelorvorlesung zur Theoretischen Mechanik grosser Universitaeten in Deutschland, Oesterreich und der Schweiz moeglichst umfassend ab.' );

INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('Gerthsen Physik', 'Weiterentwicklung der Physik durch einbeziehen modernster Themen der Physik', 'Dieter Meschede', 'Springer','PHYSIC', '2007', 'Fuer die Studierenden der Physik im Haupt- und Nebenfach ist der Gerthsen ein unverzichtbarer und kompetenter Begleiter durch das gesamte Studium, das jetzt in der Neuauflage noch preisguenstiger zu erwerben ist. Nahezu alle Studierenden beginnen mit dem Klassiker Gerthsen. Saemtliche Gebiete der Physik werden ausfuehrlich und gut verstaendlich dargestellt. Das Buch stellt alle klassischen Themen vor - Mechanik, Waermelehre, Elektrodynamik, Optik. Darauf aufbauende Themen der klassischen Physik wie die Nichtlineare Dynamik und die Relativitaetstheorie sind in logischer Reihenfolge integriert. Nach einem Kapitel ueber Teilchen und Wellen zur Einfuehrung in die mikroskopische Physik werden die Konsequenzen fuer Atome, Molekuele, Laser, feste Koerper und subatomare Teilchen vorgestellt.' );

INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('Numerische Physik: Ausgewaehlte Beispiele der Theoretischen Physik mit C++', 'wichtigsten numerischen Techniken in der Programmiersprache C++', 'Harald Wiedemann', 'Springer','PHYSIC', '2019', 'Dieses Lehrbuch stellt die Numerische Physik anhand einer Vielzahl von Beispielen aus den Bereichen Mechanik, Elektrodynamik, Optik, Statistischer Physik und Quantenmechanik dar. Der Leser lernt hier nicht nur die wichtigsten numerischen Techniken in der Programmiersprache C++ kennen, sondern erhaelt auch neue Einblicke in die Physik, die konventionelle Zugaenge nicht bieten. Das Werk schliesst damit eine Luecke zwischen den Standardlehrbuechern der Theoretischen Physik und denen der reinen Programmierung.' );

INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('Differentialgeometrie, Topologie und Physik', 'Anwendung von Geometrie und Topologie in der modernen Physik', 'Mikio Nakahara ', 'Springer','PHYSIC', '2015', 'Differentialgeometrie und Topologie sind wichtige Werkzeuge fuer die Theoretische Physik. Insbesondere finden sie Anwendung in den Gebieten der Astrophysik, der Teilchen- und Festkoerperphysik. Das vorliegende beliebte Buch, das nun erstmals ins Deutsche uebersetzt wurde, ist eine ideale Einfuehrung fuer Masterstudenten und Forscher im Bereich der theoretischen und mathematischen Physik.' );

INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('Physische Geographie kompakt', 'eine verstaendliche Einfuehrung der Physischen Geographie fuer das Grundstudium', 'Ruediger Glaser, Christiane Hauter und Dominik Faust,', 'Springer','GEO','2017', 'Physische Geographie kompakt ermoeglicht Studenten mit Haupt- oder Nebenfach Geographie wie auch Schuelern einen raschen, kompakten Einstieg in die Materie. Die didaktisch herausragenden vierfarbigen Abbildungen visualisieren die wichtigen geographischen Prozesse und erleichtern das Verstaendnis fuer die Konzepte und Theorien der Physischen Geographie. Veranschaulicht werden die Fakten an vorwiegend mitteleuropaeischen Beispielen. Der Bogen spannt sich in diesem Lehrbuch von den endogenen und exogenen Kraeften ueber die Dynamik der Atmosphaere und die Boeden der Erde bis zur Vegetation und zur naturraeumlichen Gliederung Deutschlands.' );

INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('Der Tollhauseffekt', 'wie die leugnung des klimawandels unsere planeten bedroht', 'Michael E. Mann und Tom Toles', 'Heise','GEO','2018', 'Das Buch handelt vom Spannungsfeld zwischen Politik und Wissenschaft, wobei es vor allem um die klimaforschende Wissenschaft geht. Es beschaeftigt sich mit den Manipulationen sogenannter Klimaskeptiker und deren Pseudo- und Antiwissenschaft, die allzu oft, als serioese Wissenschaft verkleidet, anerkannte Erkenntnisse und physikalische Tatsachen leugnet. So erlaeutert Michael E. Mann, verantwortlich fuer die Texte im Buch, wie wissenschaftliche Methodik funktioniert und offenbart dadurch gleichzeitig die Tragik der politischen Debatte. Er schreibt unter anderem: "Leider wurde der Begriff Skeptiker gerade im Zuge der Klimadebatte verschleppt, um etwas ganz anderes zu auszusagen. Er wird benutzt, um Beweisen auszuweichen, die man einfach nicht mag." Das Buch analysiert, deckt auf, gibt aber auch Hoffnung!');

INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('Weltbilder', 'Entwicklung und die gegenwaertige Konditionierung und Akzentuierung unseres Weltbilds', 'Hans Gebhardt und Helmuth Kiesel', 'Springer','GEO','2004', 'Ziel des vorliegenden Bandes ist es, die geschichtliche Entwicklung und die gegenwaertige Konditionierung und Akzentuierung unseres Weltbilds zu skizzieren und zu reflektieren. Die Fragen, denen die 19 Beitraege aus 13 Disziplinen nachgehen, lauten: Was koennen wir heute einigermassen zuverlaessig ueber die Entstehung und Entwicklung des Weltalls und der Erde sowie des Lebens auf der Erde sagen? Wie entstand das moderne Weltbild und welchen Anteil hatten Religion, Philosophie und Naturwissenschaften an diesem "Weltbildungsprozess"? Inwieweit ist unser Weltbild nicht nur durch Akkumulation von Wissen bestimmt, sondern in grundsaetzlicher und unhintergehbarer Weise auch durch die Beschaffenheit unseres Erkenntnisapparats und die Struktur unserer Sprache?');

INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('So erklaere ich Geografie', 'Wie dreht sich die Erde um die Sonne?', 'Schmidt Hans', 'Verlag an der Ruhr GmbH','GEO','2003', 'Die in diesem Band vorgestellten Versuche und Modelle ermutigen Ihre Schueler, die Welt der Geografie selbstaendig zu entdecken. Mithilfe einfachster Materialien wie Abschnitte von Plastikflaschen oder Bodenproben, ein Stueck Kreide oder Zeitungspapier  koennen die Jugendlichen Modellversuche zu Bodenkapillaritaet, Faltengebirgen, Vulkanismus und Co. herstellen und durchfuehren. Auch scheinbar abstrakte Themen wie Laengen- und Breitengrade, Hoehenlinien und Zentrifugalkraefte koennen so im wahrsten Sinne des Wortes „begreifbar“ gemacht werden. Gleichzeitig ueben sich Ihre Schueler in Orientierung, Kartenverstaendnis und im Messen. Dieses Unterrichtsmaterial ist geeignet fuer Lehrer an Hauptschulen, Realschulen, Gesamtschulen und Gymnasien' );

INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('Geschichte der Kartographie', 'Buch bezueglich die Geschichte der Kartographie', 'Georges Grosjean', 'Geographisches Institut der Universitaet Bern','GEO','1996', 'Ein Querschnitt durch die Geschichte der Kartographie vermittelt methodisch eine Einfuehrung in die Betrachtung und die Untersuchung von historischen Karten und materiell die Vorstellung bedeutendender Erscheinungen der schweizerischen Kartographie bis an die Schwelle der Gegenwart. Mit ausgewaehlten auslaendischen Karten werden die grossen Perioden der allgemeinen Geschichte der Kartographie angedeutet, in welche sich das schweizerische Kartenschaffen einordnen laesst.');

INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('Against Nature', 'Ordnung in der westlichen philosophischen Tradition', 'Daston und Lorraine', 'The MIT Press','PHYLO','2019', 'In diesem kurzen, praegnanten Werk der philosophischen Anthropologie fragt Lorraine Daston, warum wir trotz so vieler guter Ratschlaege zum Gegenteil staendig nach moralischen Ordnungen in natuerlichen Ordnungen suchen. Sie skizziert drei spezifische Formen der natuerlichen Ordnung in der westlichen philosophischen Tradition - spezifische Naturen, lokale Naturen und universelle Naturgesetze - und beschreibt, wie jede dieser drei natuerlichen Ordnungen dazu benutzt wurde, eine bestimmte Form des Unnatuerlichen zu definieren und sich ihr entgegenzustellen. Sie argumentiert, dass jede dieser Formen des Unnatuerlichen ebenso ausgepraegte Emotionen ausloest: Schrecken, Schrecken und Verwunderung. Daston schlaegt vor, dass die im menschlichen Koerper praktizierte menschliche Vernunft die Aufmerksamkeit der Philosophen erregen sollte, die sich traditionell nach einem transzendenten Grund sehnen, der fuer alle Arten, alle Epochen und sogar alle Planeten gilt.');

INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('Handbuch Literatur und Philosophie', 'Beruehrungspunkte zwischen Literatur und Philosophie', 'Hans Feger', 'J.B. Metzler','PHYLO','2012','Wie nah sind sich Literatur und Philosophie? Die beiden Disziplinen stehen fuer ganz unterschiedliche Formen der Welterkenntnis und der Erkenntnisvermittlung. Doch ohne das Verstaendnis des jeweils anderen Bereiches kommen die literaturwissenschaftliche und die philosophische Analyse schnell an ihre Grenzen. Dass es zahlreiche Beruehrungspunkte zwischen Literatur und Philosophie gibt, zeigt dieses Handbuch. In 16 ausfuehrlichen Kapiteln schafft es einen ueberblick ueber Problemkonstellationen, bei denen die Trennung beider Fachgebiete relativiert oder aufgehoben ist.' );

INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('Karl Popper: Logik der Forschung', 'warum unser Wissen fehlbar ist?', 'Herbert Heuth', 'Akademie Verlag','PHYLO','2013', 	'Karl Raimund Poppers (1902-1994) Hauptwerk, die Logik der Forschung (1934), gilt als Grundlagenwerk des kritischen Rationalismus. Der kritische Rationalismus zeigt, warum unser Wissen fehlbar ist und versteht den Erkenntnisfortschritt als Resultat von Hypothesenbildung und -widerlegung. Der Sammelband orientiert sich an der Gliederung der Logik der Forschung. Seine Beitraege kommentieren die jeweiligen Themen nach aktueller Forschungslage.');

INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('Praefiguration Arbeit am politischen Mythos', 'Arbeit am Mythos der Totalitarismus des 20. Jahrhunderts', 'Hans Blumenberg', 'Suhrkamp Verlag','PHYLO','2014', 'Anlaesslich einer Besprechung seiner grossen Monographie Arbeit am Mythos schreibt Hans Blumenberg am 20. Juli 1981 an den Rezensenten Goetz Mueller: Schwer faellt es mir immer, auf Rezensionen etwas zu sagen. Es ist allemal zu spaet. Doch fuehle ich mich von Ihnen zu Recht getroffen. Dem Buch fehlt ein Kapitel, das im Manuskript schon vorlag, mir aber den Geschmack an dem Buch ganz und gar verdorben hatte. Ich habe es zurueckgehalten. Man mag nach mir damit machen, was man will.');

INSERT INTO Book(name, shortDescription, author, publisher, category, publishDate, description) VALUES ('Was bedeutet das alles?', 'Einfuehrung in die Philosophie', 'Thomas Nagel', 'Reclam','PHYLO','1987', 'Nagels leicht verstaendliche Einfuehrung in die Philosophie schneidet auf engstem Raum die groessten Themen an, etwa: Woher wissen wir etwas? Was bedeuten Woerter? Was ist der Tod? Worin koennte der Sinn des Lebens bestehen? Dabei geht es Nagel nicht um Antworten, sondern um das Aufzeigen einiger philosophischer Aspekte im Zusammenhang mit diesen und aehnlichen Fragen. Ein Leser erfaehrt durch die Art der Diskussion der Themen etwas darueber, welchen Themen sich die Philosophie aus welchen Gruenden widmet und wie sie diese Themen bearbeitet.');


